In [1]:
import pandas as pd
import numpy as np

In [2]:
arr = []
for i in range(10):
    data = np.random.random(size=5)
    arr.append(data)
df = pd.DataFrame(arr)

In [3]:
df['mean'] = 0.0
for i in range(df.shape[0]):
    summ = 0.0
    cnt = 0
    for j in range(df.shape[1] - 1):
        if df.iloc[i, j] > 0.3:
            summ += df.iloc[i, j]
            cnt += 1
    if cnt != 0:
        df.iloc[i,5] = summ / cnt
    
df

          0         1         2         3         4      mean
0  0.190768  0.825435  0.880437  0.986146  0.432108  0.781031
1  0.900959  0.724417  0.756940  0.307905  0.092398  0.672555
2  0.399866  0.785975  0.854378  0.144627  0.335902  0.594030
3  0.487662  0.226110  0.709915  0.672464  0.661732  0.632943
4  0.752344  0.364886  0.754121  0.094936  0.391452  0.565701
5  0.109809  0.179923  0.574991  0.316832  0.860717  0.584180
6  0.238005  0.723148  0.221558  0.333628  0.404466  0.487081
7  0.928236  0.499758  0.761850  0.739790  0.725691  0.731065
8  0.873276  0.649342  0.493417  0.013088  0.485422  0.625364
9  0.778149  0.272662  0.382247  0.215161  0.188803  0.580198

In [4]:
df = pd.DataFrame(np.random.random((10, 5)))
mask = df > 0.3
df['mean'] = df.where(mask).mean(axis=1).fillna(0.0)
df

          0         1         2         3         4      mean
0  0.714126  0.380706  0.546702  0.566068  0.528345  0.547190
1  0.201647  0.967778  0.929343  0.594345  0.812275  0.825935
2  0.061576  0.677468  0.848464  0.525955  0.336367  0.597063
3  0.725422  0.939167  0.281410  0.650006  0.946525  0.815280
4  0.255239  0.540062  0.431221  0.932591  0.955302  0.714794
5  0.752222  0.739842  0.648616  0.876473  0.420457  0.687522
6  0.980042  0.800726  0.291861  0.245422  0.990080  0.923616
7  0.253848  0.687440  0.294399  0.045988  0.874984  0.781212
8  0.472019  0.174172  0.667517  0.107269  0.050390  0.569768
9  0.972900  0.928522  0.784956  0.732257  0.722454  0.828218