In [2]:
import numpy as np
import pandas as pd

In [3]:
df1 = pd.read_csv('titanic_with_labels.csv', index_col=0) # sep = '', delimiter = '', nrows = 10, header = None
df2 = pd.read_csv('cinema_sessions.csv', index_col=0) # sep = '', delimiter = '', nrows = 10, header = None
df1 = pd.merge(df1, df2, on='check_number')
df1['session_start'] = pd.to_datetime(df1['session_start'], format= 'mixed')

In [4]:
groups_bin = [0, 18, 50, np.inf]
labels = ['kid', 'adult', 'elderly']

# Разбиваем возраст на категории
df1['age_group'] = pd.cut(df1['age'], bins=groups_bin, labels=labels, include_lowest=True)

# Создаём бинарные колонки для каждой категории
df1['age_child']   = np.where(df1['age_group'] == 'kid', 1, 0)
df1['age_adult']   = np.where(df1['age_group'] == 'adult', 1, 0)
df1['age_elderly'] = np.where(df1['age_group'] == 'elderly', 1, 0)

# Удаляем исходный столбец возраста и категорию
df1 = df1.drop(['age', 'age_group'], axis=1)

df1

,sex,row_number,liters_drunk,drink,check_number,label,session_start,age_child,age_adult,age_elderly
0,F,79.0,2,Cola,3116,0,2025-10-30 21:00:00,0,0,1
1,M,23.0,0,Fanta,8118,0,2025-10-30 15:30:00,1,0,0
2,M,92.0,0,Fanta,2264,1,2025-10-30 22:15:00,1,0,0
3,F,52.0,5,Beerbeer,7640,1,2025-10-30 23:42:00,0,0,1
4,F,57.0,2,Beerbeer,8764,0,2025-10-30 15:30:00,0,1,0
...,...,...,...,...,...,...,...,...,...,...
9995,M,96.0,5,Beerbeer,9554,0,2025-10-30 15:30:00,0,0,1
9996,-,22.0,4,Water,9933,0,2025-10-30 22:30:00,0,1,0
9997,-,89.0,4,Beerbeer,2905,1,2025-10-30 15:34:00,0,1,0
9998,F,26.0,0,Fanta,6198,1,2025-10-30 08:42:00,0,1,0
9999,-,64.0,1,Bugbeer,6523,0,2025-10-30 07:00:00,0,1,0

In [5]:
df1['drink'] = df1['drink'].map({'Beerbeer': 1, 'Water': 0, 'Bugbeer' : 1, 'Cola' : 0, 'Strong beer' : 1, 'Fanta' : 0, 'Наше пиво' : 1})

In [6]:
# df1['session_start'].max()
bins = [6, 12, 20, 24]
labels = ['morning', 'day', 'evening']

df1['session_start_group'] = pd.cut(df1['session_start'].dt.hour, bins= bins, labels= labels, include_lowest= True)
time_dummies = pd.get_dummies(df1['session_start_group'], prefix='session')
df1 = pd.concat([df1, time_dummies], axis=1)

df1 = df1.drop(['session_start_group'], axis=1)

for col in ['session_morning', 'session_day', 'session_evening']:
    df1[col] = df1[col].astype(int)

In [9]:
df1.head(20)

,sex,row_number,liters_drunk,drink,check_number,label,session_start,age_child,age_adult,age_elderly,session_morning,session_day,session_evening
0,F,79.0,2,0,3116,0,2025-10-30 21:00:00,0,0,1,0,0,1
1,M,23.0,0,0,8118,0,2025-10-30 15:30:00,1,0,0,0,1,0
2,M,92.0,0,0,2264,1,2025-10-30 22:15:00,1,0,0,0,0,1
3,F,52.0,5,1,7640,1,2025-10-30 23:42:00,0,0,1,0,0,1
4,F,57.0,2,1,8764,0,2025-10-30 15:30:00,0,1,0,0,1,0
5,M,15.0,1,1,6235,0,2025-10-30 08:42:00,0,1,0,1,0,0
6,F,49.0,0,0,185,1,2025-10-30 06:00:00,1,0,0,1,0,0
7,M,33.0,5,0,2970,1,2025-10-30 14:15:00,0,0,1,0,1,0
8,F,5.0,0,0,6494,0,2025-10-30 14:00:00,0,1,0,0,1,0
9,M,48.0,1,0,9971,1,2025-10-30 15:30:00,0,0,1,0,1,0
10,F,78.0,99602005,0,3592,0,2025-10-30 22:15:00,0,0,1,0,0,1
11,M,32.0,2,1,2021,0,2025-10-30 07:00:00,0,1,0,1,0,0
12,F,12.0,3,0,5675,1,2025-10-30 14:15:00,0,0,1,0,1,0
13,F,16.0,5,1,1637,0,2025-10-30 15:00:00,0,0,1,0,1,0
14,F,46.0,74068055,1,7830,1,2025-10-30 15:00:00,0,1,0,0,1,0
15,F,4.0,3,0,2174,1,2025-10-30 21:00:00,1,0,0,0,0,1
16,-,1.0,4,1,8641,1,2025-10-30 15:34:00,0,0,1,0,1,0
17,-,18.0,4,0,9424,0,2025-10-30 22:30:00,1,0,0,0,0,1
18,-,83.0,2,0,3405,1,2025-10-30 06:00:00,0,1,0,1,0,0
19,M,NaN,-6,0,2468,0,2025-10-30 23:42:00,1,0,0,0,0,1